# @see Configuration schema/metadata at https://drupal.org/node/1905070
#
field.time_duration_time.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default'
      mapping:
        value:
          type: string
          label: 'Value'
